name: Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - "teams/**"

jobs:
  discover:
    name: Discover roles
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate matrix of Terraform roles
        id: set-matrix
        run: |
          matrix=$(find teams -type d -name "*-role" | \
            jq -R -s -c 'split("\n") | map(select(. != "")) | map({
              path: .,
              env: (split("/")[2]),
              team: (split("/")[1])
            })')
          echo "matrix=$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy ${{ matrix.team }} roles in ${{ matrix.env }}
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.discover.outputs.matrix) }}
    environment: ${{ matrix.env }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: androzo/terraform-deploy@main
        with:
          terraform_path: ${{ matrix.path }}
        env:
          TF_VAR_environment: ${{ matrix.env }}
          TF_VAR_team_name: ${{ matrix.team }}
          TF_VAR_region: sa-east-1
