name: Deploy team roles and policies to AWS
on:
  workflow_dispatch:
  push:
    paths:
      - "**/teams/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_OIDC_ROLE }}
          aws-region: sa-east-1
          role-session-name: GitHubActionsDeployTeamRoles

      - name: Verify AWS Role
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6 # Replace with your desired Terraform version

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./teams/team-anders/devl/deployment-role # Adjust the path to your Terraform configuration

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./teams/team-anders/devl/deployment-role

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: ./teams/team-anders/devl/deployment-role

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
        working-directory: ./teams/team-anders/devl/deployment-role
